repos:
  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py{{ cookiecutter.minimal_python_version.replace('.', '') }}-plus
        types: [python]
        language: system

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort pyarr
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black pyarr --check
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: poetry run flake8 pyarr
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy pyarr
        types: [python]
        pass_filenames: false

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
